config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users


  root 'books#index'
  #root 'users#alluser'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :books, only: [:index, :create, :show, :edit, :update, :destroy, :back] do
   end

   resources :users, only: [:index, :show, :edit, :update, :alluser]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	# 1つのUserモデルとBookモデルの関連付け
	belongs_to :user

	# バリデーションチェック
	validates :title, presence: true
	validates :opinion, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Userとの関連付け (1:N)の関係
  has_many :books, dependent: :destroy
  # 画像投稿機能
  attachment :profile_image

  # sign_in sig_up 名前入力設定 (空白禁止、２〜２０字以内)
  validates :name, presence: true, uniqueness: true, length: 2..20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
	def configure_permitted_parameters
		# sign_up時、nameのデータの操作を許可
		devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
		# sign_in時、nameのデータの操作を許可
		devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  # 投稿・一覧設定
  def index
     # Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
    @book = Book.new
     # 全てのデータを取り出して、格納
    @books = Book.all
  end

  # 投稿設定
  def create

  	# ストロングパラメータを使用
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
      ### 投稿時の条件分岐 ###
      # DBに保存
  	 if @book.save
      # サクセスメッセージ表示
      flash[:notice] = "Book was successfully created."
  	  # 投稿・一覧画面へリダイレクト
  	  redirect_to books_path
      else
      @books = Book.all
      flash[:alert] = "ERROR!!! can't be blank"
      render :index
      end

  end

  # 詳細ページ設定
  def show
    # 取得したURLを@bookに格納
    @book = Book.find(params[:id])
  end

  # 編集ページ設定
  def edit
    # 取得したURLを@bookに格納
    @book = Book.find(params[:id])
  end
  # 編集を保存
  def update
    book = Book.find(params[:id])
    # DBに上書き
    book.update(book_params)
    # 投稿・一覧ページへリダイレクト
    redirect_to book_path(book.id)
    # サクセスメッセージ表示
    flash[:notice] = "Book was successfully updated."
  end

  # 削除設定
  def destroy
    # データ（レコード）を１件取得
    book = Book.find(params[:id])
    # データ（レコード）を削除
    book.destroy
    # 投稿・一覧画面へリダイレクト
    redirect_to books_path
  end

  # 戻る設定
  def back
    # 投稿・一覧設定へリダイレクト
    redirect_to books_path
  end

  private

  # 投稿データの受け取り
  def book_params
  	params.require(:book).permit(:title, :opinion)
  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user.user_id = current_user.id

    @user.save
    # ユーザー投稿画像を表示
    @books = @user.books
  end

  def show
  	# 取得URLをuserに格納
  	@user = User.find(params[:id])
  	# 保存
  	@user.save
  	# ユーザー投稿画像を表示
  	@books = @user.books
  end

  #def alluser
   # Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
    #@user = User.new
     # 全てのデータを取り出して、格納
    #@users = User.all
  #end

  # プロフィール編集アクションを定義
  def edit
    @user = User.find(params[:id])
  end

  # プロフィール画像保存
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :iintroduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/book.html.erb
<%= form_for(@book, url: '/books') do |f| %>
<% if @book.errors.any? %>
<%= @book.errors.count %>件のエラー
<% @book.errors.full_messages.each do |book| %>
<%= message %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

	<p>Title</p>
	<%= f.text_field :title %>
	<p>Opinion </p>
	<%= f.text_area :opinion  %>
	<br><%= f.submit 'Update Book' %>

<% end %>

<!-- 編集画面にアクセス -->
<%= link_to "Show", book_path(@book.id) %>
|
<!-- 投稿・一覧画面に戻る -->
<%= link_to 'Back', '/books' %>

app/views/books/index.html.erb
<!-- 新規投稿部分 -->
<h2>New book</h2>
<!-- form_for部分 -->
<%= form_for(@book, url: '/books') do |f| %>

  <!-- 投稿・更新時にサクセスメッセージ表示 -->
  <% if flash[:notice] %>
    <div class = "flash">
    <%= flash[:notice] %>
    </div>
  <% end %>

  <!-- エラーメッセージ -->
  <% if flash[:alert] %>
   <div class = "flash">
    <%= flash[:alert] %>
    </div>
  <% end %>

<!-- タイトル記入 -->
<h5>Title</h5>
<%= f.text_field :title %>

<!-- 本文記入 -->
<h5>Opinion</h5>
<%= f.text_area :opinion %>

<br><%= f.submit 'Create Book' %>
<% end %>


<!-- 一覧表示部分 -->
<h2>Books</h2>
<table>

  <!-- 見出し表示 -->
  <thead>
    <tr>
      <th> Title </th>
      <th></th>
      <th> Opinion </th>
    </tr>
  </thead>

  <!-- 本文表示 -->
  <tbody>
    <% @books.each do |book| %>

    <tr>
      <td> <%= book.title %> </td>
      <td></td>
      <td> <%= book.opinion  %> </td>
      <td></td>
      <!-- 詳細ボタン -->
      <td> <%= link_to "Show",book_path(book.id) %> </td>
      <td></td>
      <!-- 編集ボタン -->
      <td> <%= link_to "Edit",edit_book_path(book.id) %></td>
      <td></td>
       <!-- 削除ボタン -->
      <td> <%= link_to "Destroy",book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>

    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<!-- 投稿・更新時にサクセスメッセージ表示 -->
<% if flash[:notice] %>
	<div class = "flash">
		<%= flash[:notice] %>
	</div>
<% end %>


<p>Title: <%= @book.title %></p>
<p>Opinion : <%= @book.opinion  %></p>

<!-- 編集画面にアクセス -->
<%= link_to "Edit", edit_book_path(@book.id) %>
|
<!-- 投稿・一覧画面に戻る -->
<%= link_to 'Back', '/books' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meshiterro</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>


<div id="slidemenu">
  <ul class="nav navbar-nav" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
    <% if user_signed_in? %>
      <li class="">
        <%= link_to 'Home', books_path %>
      </li>
      <li class="">
        <%= link_to 'User', books_path %>
      </li>
      <li class="">
        <%= link_to 'Books', books_path %>
      </li>
      <li class="">
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>
      <li class="">
      <%= link_to 'マイページ', user_path(current_user.id) %>
      </li>
    <% else %>
      <li class="">
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li class="">
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>


    <%= yield %>  <!-- 画面の呼び出し -->

  </body>
</html>

app/views/users/alluser.html.erb
<!-- 一覧表示部分 -->
<h2>Users</h2>
<table>

  <!-- 見出し表示 -->
  <thead>
    <tr>
      <th> image </th>
      <th></th>
      <th> name </th>
    </tr>
  </thead>

  <!-- 本文表示 -->
  <tbody>
    <% @users.each do |user| %>

    <tr>
      <td> <%= user.profile_image_id %> </td>
      <td></td>
      <td> <%= user.name  %> </td>
      <td></td>

      <!-- 投稿詳細ボタン -->
      <td> <%= link_to "Show",book_path(book.id) %> </td>
      <td></td>
    </tr>

    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

<div class="form-group has-icon">

  <!-- 名前編集 -->
  <label class="control-label sr-only" for="inputEmail">Name</label>
    <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
      <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
</div>

<!-- プロフィール画像表示 -->
<div class="form-group has-icon">
  <label class="control-label sr-only" for="inputEmail">Image</label>

  <!-- 画像選択用ボタン生成 -->
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>

   <!-- 画像埋め込み -->
  <div class="user-edit-image">
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
  </div>

      Introdoction
      <%= f.text_area :introduction %>
  </div>
</div>

<!-- UPDATEボタン -->
<%= f.submit "Update User",class:"btn btn-lg btn-block btn-base-1 mt-20" %>


<%= link_to "Show", book_path(@book.id) %>

<% end %>

app/views/users/show.html.erb
<!-- プロフィール画像の表示 -->
<div class="profile-container">
    <h3 class="profile-name"><%= @user.name %></h3>
    <%= @user.introduction %>
    <%= attachment_image_tag @user,:profile_image, :fill,60,60,format'jpeg', class: "img-circle pull-left profile-img",fallback:"no_image.jpg" %>
    <!--<%= image_tag('no_image.jpg',class:"img-circle pull-left profile-img",style:"width: 100px; hight: 100px;") %>-->
    <% if @user.id == current_user.id %>
      <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right" %></p>c
    <% end %>
</div>